name: Build and Push MSSQL Server Windows Docker Image

on:
  workflow_dispatch:
    inputs:
     sql_version:
        description: 'SQL Server Version'
        required: true
        default: '2022'
        type: choice
        options:
        - '2022'
        - '2019'

     win_version:
        description: 'Windows Version'
        required: true
        default: '2022'
        type: choice
        options:
        - '2022'
        - '2019'

jobs:
  build_and_deploy:
    runs-on: windows-${{ inputs.win_version }}
    name: Build and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build and Push
        run: |
          if (-not $env:SQL_VERSION) { $env:SQL_VERSION = '2022' }
          if (-not $env:WIN_VERSION) { $env:WIN_VERSION = 'ltsc2022' }
          docker build --build-arg SQL_VERSION=$env:SQL_VERSION --build-arg WIN_VERSION=$env:WIN_VERSION -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mssqlserver:$env:SQL_VERSION-$env:WIN_VERSION .\how_to_run_mssqlserver_in_windows_container
        env:
          SQL_VERSION: ${{ inputs.sql_version }}
          WIN_VERSION: ltsc${{ inputs.win_version }}
